 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA', '.']
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _SERVICE_NAME: acme-user-prod
  _GCR_HOSTNAME: gcr.io