name: Trigger auto deployment for acmeusercicd

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/acmeusercicd-AutoDeployTrigger-a2ba98e4-07ad-4433-a0e9-56132fdafef9.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acmeenvironment.azurecr.io
          username: ${{ secrets.ACMEUSERCICD_REGISTRY_USERNAME }}
          password: ${{ secrets.ACMEUSERCICD_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acmeenvironment.azurecr.io/acmeusercicd:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACMEUSERCICD_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n acmeusercicd -g acmerg --server acmeenvironment.azurecr.io --username  ${{ secrets.ACMEUSERCICD_REGISTRY_USERNAME }} --password ${{ secrets.ACMEUSERCICD_REGISTRY_PASSWORD }}
            az containerapp update -n acmeusercicd -g acmerg --image acmeenvironment.azurecr.io/acmeusercicd:${{ github.sha }}
